# Generated by Django 4.2.7 on 2025-11-29 17:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('content', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('note', 'Note'), ('task', 'Task'), ('link', 'Link'), ('code', 'Code Snippet'), ('document', 'Document')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal')], db_index=True, default='personal', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('is_starred', models.BooleanField(db_index=True, default=False)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='documents/%Y/%m/%d/')),
                ('language', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('pink', 'Pink Theme')], default='pink', max_length=20)),
                ('storage_used', models.BigIntegerField(default=0)),
                ('items_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UniversalNote',
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['user', 'content_type'], name='notes_app_c_user_id_42dada_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['user', 'is_starred'], name='notes_app_c_user_id_705454_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['user', 'is_completed'], name='notes_app_c_user_id_3c34a8_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['user', 'due_date'], name='notes_app_c_user_id_3dc3e9_idx'),
        ),
    ]
