# Generated by Django 4.2.7 on 2025-12-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_contentitem_userprofile_delete_universalnote_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentitem',
            name='notes_app_c_user_id_42dada_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentitem',
            name='notes_app_c_user_id_705454_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentitem',
            name='notes_app_c_user_id_3c34a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentitem',
            name='notes_app_c_user_id_3dc3e9_idx',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='reminder',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('note', 'Note'), ('task', 'Task'), ('link', 'Link'), ('code', 'Code Snippet'), ('document', 'Document')], default='note', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
